// <auto-generated />
using System;
using BloodClockTowerScriptEditor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodClockTowerScriptEditor.Migrations
{
    [DbContext(typeof(RoleTemplateContext))]
    [Migration("20260921013710_AddRoleSource")]
    partial class AddRoleSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BloodClockTowerScriptEditor.Models.RoleReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReminderText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleReminders");
                });

            modelBuilder.Entity("BloodClockTowerScriptEditor.Models.RoleTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ability")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("FirstNight")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstNightReminder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flavor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("official_id");

                    b.Property<int>("OriginalOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OtherNight")
                        .HasColumnType("REAL");

                    b.Property<string>("OtherNightReminder")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Setup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("special");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Edition");

                    b.HasIndex("IsOfficial");

                    b.HasIndex("Name");

                    b.HasIndex("Team");

                    b.ToTable("RoleTemplates");
                });

            modelBuilder.Entity("BloodClockTowerScriptEditor.Models.RoleReminder", b =>
                {
                    b.HasOne("BloodClockTowerScriptEditor.Models.RoleTemplate", "Role")
                        .WithMany("Reminders")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BloodClockTowerScriptEditor.Models.RoleTemplate", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
